version: '3.1'

services:
  postgres:
    image: postgres:16
    restart: always
    ports:
      - ${TRACK__DATABASE_PORT}:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${TRACK__DATABASE_PASSWORD}
      POSTGRES_USER: ${TRACK__DATABASE_USER}
      POSTGRES_DB: ${TRACK__DATABASE_NAME}

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "4318:4318"
      - "4317:4317"
    environment:
      - LOG_LEVEL=debug
    networks:
      - jaeger-example

networks:
  jaeger-example: