env_files = ["./.env"]

[tasks.start_postgres]
command = "docker"
args = ["compose", "up", "postgres"]

[tasks.stop_postgres]
command = "docker"
args = ["compose", "down", "postgres"]

[tasks.start_jaeger]
command = "docker"
args = ["compose", "up", "jaeger"]

[tasks.stop_jaeger]
command = "docker"
args = ["compose", "down", "jaeger"]

[tasks.start_docker_all]
command = "docker"
args = ["compose", "up"]

[tasks.stop_docker_all]
command = "docker"
args = ["compose", "down"]

[tasks.start_server]
command = "cargo"
args = ["run"]

[tasks.start_all]
run_task = { name = [
    "start_docker_all",
    "start_server",
], fork = true, parallel = true }
